# Generated by Django 4.2.1 on 2023-06-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kifu_app', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='title',
            field=models.CharField(default='hoge', max_length=100),
        ),
    ]
