# Generated by Django 4.2.1 on 2023-06-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kifu_app', '0004_donation_desctiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='desctiption',
            new_name='description',
        ),
    ]
